### PR TITLE
deprecation fixes

### LINKED ISSUE #37: Compiling errors
Good day, dears. 
Could you please advice me with following situation ?
After step 'Make' i got few errors:

Log:
segment.c:108:5: error: must use 'struct' tag to refer to type 'AVCodecContext'
    AVCodecContext *codec_ctx;
    ^
    struct 
segment.c:111:15: warning: assigning to 'AVInputFormat *' (aka 'struct AVInputFormat *') from 'const struct AVInputFormat *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    seg->ifmt = fmt->iformat;
              ^ ~~~~~~~~~~~~
segment.c:129:34: error: cannot assign to non-static data member 'oformat' with const-qualified type 'const struct AVOutputFormat *'
    seg->fmt_ctx->oformat->flags &= AVFMT_NOFILE;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/opt/homebrew/Cellar/ffmpeg/5.0/include/libavformat/avformat.h:1221:34: note: non-static data member 'oformat' declared const here
    const struct AVOutputFormat *oformat;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
segment.c:137:25: error: implicit declaration of function 'avcodec_alloc_context3' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            codec_ctx = avcodec_alloc_context3(NULL);
                        ^
segment.c:137:25: note: did you mean 'avio_alloc_context'?
/opt/homebrew/Cellar/ffmpeg/5.0/include/libavformat/avio.h:409:14: note: 'avio_alloc_context' declared here
AVIOContext *avio_alloc_context(
             ^
segment.c:137:23: warning: incompatible integer to pointer conversion assigning to 'struct AVCodecContext *' from 'int' [-Wint-conversion]
            codec_ctx = avcodec_alloc_context3(NULL);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
segment.c:138:13: error: implicit declaration of function 'avcodec_parameters_to_context' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            avcodec_parameters_to_context(codec_ctx, in_stream->codecpar);
            ^
segment.c:138:13: note: did you mean 'avcodec_parameters_copy'?
/opt/homebrew/Cellar/ffmpeg/5.0/include/libavcodec/codec_par.h:222:5: note: 'avcodec_parameters_copy' declared here
int avcodec_parameters_copy(AVCodecParameters *dst, const AVCodecParameters *src);
    ^
segment.c:139:69: error: incomplete definition of type 'struct AVCodecContext'
            out_stream = avformat_new_stream(seg->fmt_ctx, codec_ctx->codec);
                                                           ~~~~~~~~~^
/opt/homebrew/Cellar/ffmpeg/5.0/include/libavcodec/codec.h:195:8: note: forward declaration of 'struct AVCodecContext'
struct AVCodecContext;
       ^
segment.c:141:13: error: implicit declaration of function 'avcodec_free_context' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            avcodec_free_context(&codec_ctx);
            ^
segment.c:141:13: note: did you mean 'avformat_free_context'?
/opt/homebrew/Cellar/ffmpeg/5.0/include/libavformat/avformat.h:1903:6: note: 'avformat_free_context' declared here
void avformat_free_context(AVFormatContext *s);
     ^
2 warnings and 6 errors generated.
make: *** [segment.o] Error 1

---------------
How can i fix it? I have succesfully installed "ffmpeg" via Homebrew and not found  "ffserver", and decided to install this software.

### LINKED ISSUE #38: Can't compile on ubuntu 22.04
```
cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` -pthread -c segment.c
cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` -pthread -c buffer.c
cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` -pthread -c publisher.c
#cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` `pkg-config --libs libavformat libavcodec libavutil` -pthread -o server segment.o buffer.o publisher.o server2.c
cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` -pthread -o server segment.o buffer.o publisher.o server2.c `pkg-config --libs libavformat libavcodec libavutil`
server2.c: In function ‘accept_thread’:
server2.c:301:66: warning: passing argument 4 of ‘av_opt_get’ from incompatible pointer type [-Wincompatible-pointer-types]
  301 |             av_opt_get(client, "method", AV_OPT_SEARCH_CHILDREN, &method);
      |                                                                  ^~~~~~~
      |                                                                  |
      |                                                                  char **
In file included from server2.c:8:
/usr/include/x86_64-linux-gnu/libavutil/opt.h:757:84: note: expected ‘uint8_t **’ {aka ‘unsigned char **’} but argument is of type ‘char **’
  757 | int av_opt_get         (void *obj, const char *name, int search_flags, uint8_t   **out_val);
      |                                                                        ~~~~~~~~~~~~^~~~~~~
server2.c:302:68: warning: passing argument 4 of ‘av_opt_get’ from incompatible pointer type [-Wincompatible-pointer-types]
  302 |             av_opt_get(client, "resource", AV_OPT_SEARCH_CHILDREN, &resource);
      |                                                                    ^~~~~~~~~
      |                                                                    |
      |                                                                    char **
In file included from server2.c:8:
/usr/include/x86_64-linux-gnu/libavutil/opt.h:757:84: note: expected ‘uint8_t **’ {aka ‘unsigned char **’} but argument is of type ‘char **’
  757 | int av_opt_get         (void *obj, const char *name, int search_flags, uint8_t   **out_val);
      |                                                                        ~~~~~~~~~~~~^~~~~~~
server2.c: In function ‘main’:
server2.c:440:5: warning: ‘av_register_all’ is deprecated [-Wdeprecated-declarations]
  440 |     av_register_all();
      |     ^~~~~~~~~~~~~~~
In file included from server2.c:9:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:1955:6: note: declared here
 1955 | void av_register_all(void);
      |      ^~~~~~~~~~~~~~~

```

### PR DESCRIPTION
**Pull request by Ckath**
- several type arguments changed from char * to uint8_t *
- several things now return const
- some functions are just gone
- set flags directly on context, oformat->flags is readonly
- no need to copy context anymore for out stream

this lets it compile against modern ffmpeg API. I havent found a great deal of info on this s mostly went fixing one thing to another until I got it to compile again and it seems to be fine. do let me know if there are any unexpected issues coming from no longer copying context among, the rest I'm sure should be fine.

the choice has been made to not get rid of other commented out parts or do too much formatting, this is purely a hotfix to get it compiling again with modern ffmpeg

most likely
closes #38 
closes #37 

I do not know how actively this repo is looked at but I've also merged this and the previous pr into if anyone is so inclined to try it https://github.com/Ckath/mkvserver_mk2/tree/fork_tip

### CODE REVIEW

**Comment by klaxa** [comment]
Hi, this project has been continued at [https://github.com/klaxa/ffserver](https://github.com/klaxa/ffserver). I can merge this PR, but I think it would be more useful to adopt it for the ffserver project.

**Comment by Ckath** [comment]
ah, my bad. but thanks
I never really touched ffserver and had the old version of this in use on an old vps that ran into the api deprecation when I moved it to new vps recently
I assume the ffserver project can 1:1 replace the usecase of streaming local file, thats my main usecase atm as it saves bandwidth of streaming to and from

I see ffserver running into some similar things I'll throw you a PR if I get around to it for that. might take longer if it has more complex muxing or other fancy things this all lacked
