### ISSUE TITLE
Can't compile on centos 7 and Ubuntu 16.04

### ISSUE THREAD

**Issue by onestay** [klaxa/mkvserver_mk2#9]
I get the following error when trying to compile on Ubuntu 16.04 or Centos 7 after running make.

```
`cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` -pthread -c segment.c
segment.c: In function ‘segment_init’:
segment.c:138:13: warning: implicit declaration of function ‘avcodec_parameters_to_context’ [-Wimplicit-function-declaration]
             avcodec_parameters_to_context(codec_ctx, in_stream->codecpar);
             ^
segment.c:138:63: error: ‘AVStream’ has no member named ‘codecpar’
             avcodec_parameters_to_context(codec_ctx, in_stream->codecpar);
                                                               ^
segment.c:146:13: warning: implicit declaration of function ‘avcodec_parameters_copy’ [-Wimplicit-function-declaration]
             ret = avcodec_parameters_copy(out_stream->codecpar, in_stream->codecpar);
             ^
segment.c:146:53: error: ‘AVStream’ has no member named ‘codecpar’
             ret = avcodec_parameters_copy(out_stream->codecpar, in_stream->codecpar);
                                                     ^
segment.c:146:74: error: ‘AVStream’ has no member named ‘codecpar’
             ret = avcodec_parameters_copy(out_stream->codecpar, in_stream->codecpar);
                                                                          ^
make: *** [segment.o] Error 1`
```

**Comment by klaxa** [comment]
It looks like your ffmpeg library is too old. I usually build against the latest git whenever I build.

The field AVStream->codecpar has been around for a while (a quick git blame shows the last modification was October 2017), so I think updating your libraries should fix this problem.

**Comment by rishabh9** [comment]
Hi @klaxa I too am having problems building the server.
I have taken the latest FFMPEG from Git and built it.
But while building the mkv server I get the following error. Any pointers?

```
root@fbm:/home/ubuntu/linux-x86_64/mkvserver# cc -g -Wall -I/home/ubuntu/linux-x86_64/include -L/home/ubuntu/linux-x86_64/lib -lavformat -lavcodec -lavutil -pthread -o server segment.c buffer.c publisher.c server2.c
server2.c: In function 'accept_thread':
server2.c:301:66: warning: passing argument 4 of 'av_opt_get' from incompatible pointer type [-Wincompatible-pointer-types]
             av_opt_get(client, "method", AV_OPT_SEARCH_CHILDREN, &method);
                                                                  ^
In file included from server2.c:8:0:
/home/ubuntu/linux-x86_64/include/libavutil/opt.h:736:5: note: expected 'uint8_t ** {aka unsigned char **}' but argument is of type 'char **'
 int av_opt_get         (void *obj, const char *name, int search_flags, uint8_t   **out_val);
     ^
server2.c:302:68: warning: passing argument 4 of 'av_opt_get' from incompatible pointer type [-Wincompatible-pointer-types]
             av_opt_get(client, "resource", AV_OPT_SEARCH_CHILDREN, &resource);
                                                                    ^
In file included from server2.c:8:0:
/home/ubuntu/linux-x86_64/include/libavutil/opt.h:736:5: note: expected 'uint8_t ** {aka unsigned char **}' but argument is of type 'char **'
 int av_opt_get         (void *obj, const char *name, int search_flags, uint8_t   **out_val);
     ^
server2.c: In function 'main':
server2.c:440:5: warning: 'av_register_all' is deprecated [-Wdeprecated-declarations]
     av_register_all();
     ^
In file included from server2.c:9:0:
/home/ubuntu/linux-x86_64/include/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^
/tmp/ccvDx3wt.o: In function `av_make_error_string':
/home/ubuntu/linux-x86_64/include/libavutil/error.h:111: undefined reference to `av_strerror'
/tmp/ccvDx3wt.o: In function `segment_free':
/home/ubuntu/linux-x86_64/mkvserver/segment.c:18: undefined reference to `avformat_free_context'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:19: undefined reference to `av_free'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:20: undefined reference to `av_free'
/tmp/ccvDx3wt.o: In function `segment_close':
/home/ubuntu/linux-x86_64/mkvserver/segment.c:95: undefined reference to `av_write_trailer'
/tmp/ccvDx3wt.o: In function `segment_init':
/home/ubuntu/linux-x86_64/mkvserver/segment.c:118: undefined reference to `av_malloc'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:121: undefined reference to `avio_alloc_context'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:123: undefined reference to `avformat_alloc_output_context2'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:124: undefined reference to `av_opt_set_int'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:137: undefined reference to `avcodec_alloc_context3'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:138: undefined reference to `avcodec_parameters_to_context'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:139: undefined reference to `avformat_new_stream'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:141: undefined reference to `avcodec_free_context'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:146: undefined reference to `avcodec_parameters_copy'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:151: undefined reference to `av_dict_copy'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:160: undefined reference to `avformat_write_header'
/home/ubuntu/linux-x86_64/mkvserver/segment.c:161: undefined reference to `avio_flush'
/tmp/cchh1KoV.o: In function `client_disconnect':
/home/ubuntu/linux-x86_64/mkvserver/publisher.c:34: undefined reference to `av_write_trailer'
/home/ubuntu/linux-x86_64/mkvserver/publisher.c:35: undefined reference to `avio_close'
/home/ubuntu/linux-x86_64/mkvserver/publisher.c:36: undefined reference to `avformat_free_context'
/tmp/ccSyMRK9.o: In function `av_make_error_string':
/home/ubuntu/linux-x86_64/include/libavutil/error.h:111: undefined reference to `av_strerror'
/tmp/ccSyMRK9.o: In function `read_thread':
/home/ubuntu/linux-x86_64/mkvserver/server2.c:64: undefined reference to `avformat_find_stream_info'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:76: undefined reference to `avcodec_alloc_context3'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:79: undefined reference to `avcodec_parameters_to_context'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:94: undefined reference to `av_gettime_relative'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:98: undefined reference to `av_read_frame'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:109: undefined reference to `av_rescale_q'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:110: undefined reference to `av_gettime_relative'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:115: undefined reference to `av_gettime_relative'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:132: undefined reference to `av_write_frame'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:133: undefined reference to `av_packet_unref'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:146: undefined reference to `avformat_close_input'
/tmp/ccSyMRK9.o: In function `write_segment':
/home/ubuntu/linux-x86_64/mkvserver/server2.c:178: undefined reference to `avformat_alloc_context'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:184: undefined reference to `av_malloc'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:185: undefined reference to `avio_alloc_context'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:188: undefined reference to `avformat_open_input'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:191: undefined reference to `av_free'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:194: undefined reference to `avformat_find_stream_info'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:197: undefined reference to `av_free'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:202: undefined reference to `av_read_frame'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:211: undefined reference to `av_write_frame'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:212: undefined reference to `av_packet_unref'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:215: undefined reference to `avformat_close_input'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:216: undefined reference to `av_free'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:222: undefined reference to `avformat_close_input'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:223: undefined reference to `av_free'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:224: undefined reference to `avformat_free_context'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:225: undefined reference to `avio_context_free'
/tmp/ccSyMRK9.o: In function `accept_thread':
/home/ubuntu/linux-x86_64/mkvserver/server2.c:250: undefined reference to `av_dict_set'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:255: undefined reference to `av_dict_set_int'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:260: undefined reference to `av_dict_set_int'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:265: undefined reference to `avio_open2'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:279: undefined reference to `avio_accept'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:291: undefined reference to `av_dict_set'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:301: undefined reference to `av_opt_get'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:302: undefined reference to `av_opt_get'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:300: undefined reference to `avio_handshake'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:318: undefined reference to `av_opt_set_int'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:319: undefined reference to `av_log'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:325: undefined reference to `avio_close'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:330: undefined reference to `avio_close'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:334: undefined reference to `avformat_alloc_output_context2'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:348: undefined reference to `avcodec_alloc_context3'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:349: undefined reference to `avcodec_parameters_to_context'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:350: undefined reference to `avformat_new_stream'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:351: undefined reference to `avcodec_free_context'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:357: undefined reference to `avcodec_parameters_copy'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:362: undefined reference to `av_dict_copy'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:370: undefined reference to `avformat_write_header'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:381: undefined reference to `avio_close'
/tmp/ccSyMRK9.o: In function `main':
/home/ubuntu/linux-x86_64/mkvserver/server2.c:440: undefined reference to `av_register_all'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:441: undefined reference to `avformat_network_init'
/home/ubuntu/linux-x86_64/mkvserver/server2.c:443: undefined reference to `avformat_open_input'
collect2: error: ld returned 1 exit status
root@fbm:/home/ubuntu/linux-x86_64/mkvserver# 
```
