### ISSUE TITLE
Cannot build on Ubuntu 16.04, 17.10, 18.04, or Debian 9.4

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [klaxa/mkvserver_mk2#12]
On all of these OSes I get build errors. For example, in 18.04 I get

```
cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` `pkg-config --libs libavformat libavcodec libavutil` -pthread -o server segment.o buffer.o publisher.o server2.c
server2.c: In function ‘accept_thread’:
server2.c:301:66: warning: passing argument 4 of ‘av_opt_get’ from incompatible pointer type [-Wincompatible-pointer-types]
             av_opt_get(client, "method", AV_OPT_SEARCH_CHILDREN, &method);
                                                                  ^
In file included from server2.c:8:0:
/usr/include/x86_64-linux-gnu/libavutil/opt.h:737:5: note: expected ‘uint8_t ** {aka unsigned char **}’ but argument is of type ‘char **’
 int av_opt_get         (void *obj, const char *name, int search_flags, uint8_t   **out_val);
     ^~~~~~~~~~
server2.c:302:68: warning: passing argument 4 of ‘av_opt_get’ from incompatible pointer type [-Wincompatible-pointer-types]
             av_opt_get(client, "resource", AV_OPT_SEARCH_CHILDREN, &resource);
                                                                    ^
In file included from server2.c:8:0:
/usr/include/x86_64-linux-gnu/libavutil/opt.h:737:5: note: expected ‘uint8_t ** {aka unsigned char **}’ but argument is of type ‘char **’
 int av_opt_get         (void *obj, const char *name, int search_flags, uint8_t   **out_val);
     ^~~~~~~~~~
segment.o: In function `av_make_error_string':
/usr/include/x86_64-linux-gnu/libavutil/error.h:111: undefined reference to `av_strerror'
segment.o: In function `segment_free':
/root/t/mkvserver_mk2-master/segment.c:18: undefined reference to `avformat_free_context'
/root/t/mkvserver_mk2-master/segment.c:19: undefined reference to `av_free'
/root/t/mkvserver_mk2-master/segment.c:20: undefined reference to `av_free'
segment.o: In function `segment_close':
/root/t/mkvserver_mk2-master/segment.c:95: undefined reference to `av_write_trailer'
segment.o: In function `segment_init':
/root/t/mkvserver_mk2-master/segment.c:118: undefined reference to `av_malloc'
/root/t/mkvserver_mk2-master/segment.c:121: undefined reference to `avio_alloc_context'
/root/t/mkvserver_mk2-master/segment.c:123: undefined reference to `avformat_alloc_output_context2'
/root/t/mkvserver_mk2-master/segment.c:124: undefined reference to `av_opt_set_int'
/root/t/mkvserver_mk2-master/segment.c:137: undefined reference to `avcodec_alloc_context3'
/root/t/mkvserver_mk2-master/segment.c:138: undefined reference to `avcodec_parameters_to_context'
/root/t/mkvserver_mk2-master/segment.c:139: undefined reference to `avformat_new_stream'
/root/t/mkvserver_mk2-master/segment.c:141: undefined reference to `avcodec_free_context'
/root/t/mkvserver_mk2-master/segment.c:146: undefined reference to `avcodec_parameters_copy'
/root/t/mkvserver_mk2-master/segment.c:151: undefined reference to `av_dict_copy'
/root/t/mkvserver_mk2-master/segment.c:160: undefined reference to `avformat_write_header'
/root/t/mkvserver_mk2-master/segment.c:161: undefined reference to `avio_flush'
publisher.o: In function `client_disconnect':
/root/t/mkvserver_mk2-master/publisher.c:34: undefined reference to `av_write_trailer'
/root/t/mkvserver_mk2-master/publisher.c:35: undefined reference to `avio_close'
/root/t/mkvserver_mk2-master/publisher.c:36: undefined reference to `avformat_free_context'
/tmp/ccDCmLsD.o: In function `av_make_error_string':
/usr/include/x86_64-linux-gnu/libavutil/error.h:111: undefined reference to `av_strerror'
/tmp/ccDCmLsD.o: In function `read_thread':
/root/t/mkvserver_mk2-master/server2.c:64: undefined reference to `avformat_find_stream_info'
/root/t/mkvserver_mk2-master/server2.c:76: undefined reference to `avcodec_alloc_context3'
/root/t/mkvserver_mk2-master/server2.c:79: undefined reference to `avcodec_parameters_to_context'
/root/t/mkvserver_mk2-master/server2.c:94: undefined reference to `av_gettime_relative'
/root/t/mkvserver_mk2-master/server2.c:98: undefined reference to `av_read_frame'
/root/t/mkvserver_mk2-master/server2.c:109: undefined reference to `av_rescale_q'
/root/t/mkvserver_mk2-master/server2.c:110: undefined reference to `av_gettime_relative'
/root/t/mkvserver_mk2-master/server2.c:115: undefined reference to `av_gettime_relative'
/root/t/mkvserver_mk2-master/server2.c:132: undefined reference to `av_write_frame'
/root/t/mkvserver_mk2-master/server2.c:133: undefined reference to `av_packet_unref'
/root/t/mkvserver_mk2-master/server2.c:146: undefined reference to `avformat_close_input'
/tmp/ccDCmLsD.o: In function `write_segment':
/root/t/mkvserver_mk2-master/server2.c:178: undefined reference to `avformat_alloc_context'
/root/t/mkvserver_mk2-master/server2.c:184: undefined reference to `av_malloc'
/root/t/mkvserver_mk2-master/server2.c:185: undefined reference to `avio_alloc_context'
/root/t/mkvserver_mk2-master/server2.c:188: undefined reference to `avformat_open_input'
/root/t/mkvserver_mk2-master/server2.c:191: undefined reference to `av_free'
/root/t/mkvserver_mk2-master/server2.c:194: undefined reference to `avformat_find_stream_info'
/root/t/mkvserver_mk2-master/server2.c:197: undefined reference to `av_free'
/root/t/mkvserver_mk2-master/server2.c:202: undefined reference to `av_read_frame'
/root/t/mkvserver_mk2-master/server2.c:211: undefined reference to `av_write_frame'
/root/t/mkvserver_mk2-master/server2.c:212: undefined reference to `av_packet_unref'
/root/t/mkvserver_mk2-master/server2.c:215: undefined reference to `avformat_close_input'
/root/t/mkvserver_mk2-master/server2.c:216: undefined reference to `av_free'
/root/t/mkvserver_mk2-master/server2.c:222: undefined reference to `avformat_close_input'
/root/t/mkvserver_mk2-master/server2.c:223: undefined reference to `av_free'
/root/t/mkvserver_mk2-master/server2.c:224: undefined reference to `avformat_free_context'
/root/t/mkvserver_mk2-master/server2.c:225: undefined reference to `avio_context_free'
/tmp/ccDCmLsD.o: In function `accept_thread':
/root/t/mkvserver_mk2-master/server2.c:250: undefined reference to `av_dict_set'
/root/t/mkvserver_mk2-master/server2.c:255: undefined reference to `av_dict_set_int'
/root/t/mkvserver_mk2-master/server2.c:260: undefined reference to `av_dict_set_int'
/root/t/mkvserver_mk2-master/server2.c:265: undefined reference to `avio_open2'
/root/t/mkvserver_mk2-master/server2.c:279: undefined reference to `avio_accept'
/root/t/mkvserver_mk2-master/server2.c:291: undefined reference to `av_dict_set'
/root/t/mkvserver_mk2-master/server2.c:301: undefined reference to `av_opt_get'
/root/t/mkvserver_mk2-master/server2.c:302: undefined reference to `av_opt_get'
/root/t/mkvserver_mk2-master/server2.c:300: undefined reference to `avio_handshake'
/root/t/mkvserver_mk2-master/server2.c:318: undefined reference to `av_opt_set_int'
/root/t/mkvserver_mk2-master/server2.c:319: undefined reference to `av_log'
/root/t/mkvserver_mk2-master/server2.c:325: undefined reference to `avio_close'
/root/t/mkvserver_mk2-master/server2.c:330: undefined reference to `avio_close'
/root/t/mkvserver_mk2-master/server2.c:334: undefined reference to `avformat_alloc_output_context2'
/root/t/mkvserver_mk2-master/server2.c:348: undefined reference to `avcodec_alloc_context3'
/root/t/mkvserver_mk2-master/server2.c:349: undefined reference to `avcodec_parameters_to_context'
/root/t/mkvserver_mk2-master/server2.c:350: undefined reference to `avformat_new_stream'
/root/t/mkvserver_mk2-master/server2.c:351: undefined reference to `avcodec_free_context'
/root/t/mkvserver_mk2-master/server2.c:357: undefined reference to `avcodec_parameters_copy'
/root/t/mkvserver_mk2-master/server2.c:362: undefined reference to `av_dict_copy'
/root/t/mkvserver_mk2-master/server2.c:370: undefined reference to `avformat_write_header'
/root/t/mkvserver_mk2-master/server2.c:381: undefined reference to `avio_close'
/tmp/ccDCmLsD.o: In function `main':
/root/t/mkvserver_mk2-master/server2.c:440: undefined reference to `av_register_all'
/root/t/mkvserver_mk2-master/server2.c:441: undefined reference to `avformat_network_init'
/root/t/mkvserver_mk2-master/server2.c:443: undefined reference to `avformat_open_input'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'server' failed
make: *** [server] Error 1
```

Is there any more detail on what OS or what ffmpeg version I should be using? Readme just says ffmpeg should be "recent".

**Comment by homerobono** [comment]
Can't build on Mint 18 too. Same 'undefined reference' errors, with ffmpeg and libavutils version 3.4, though.

**Comment by oddstr13** [comment]
`apt install pkg-config libavformat-dev libavcodec-dev libavutil-dev`

**Comment by SirHamburger** [comment]
hi,
i'm working on linux mint 19.1 and have the same issues @oddstr13 i've all dependencys updated but it didn't help. Did anyone find a solution?

**Comment by oddstr13** [comment]
@SirHamburger Installing the above depdendencies fixed the issues described in this issue.
When installing on Debian 9, I had the additional issue of old ffmpeg version (ffmpeg version `3.2.12-1~deb9u1`, 2017-05-16).
`avio_context_free` was added in FFmpeg/FFmpeg@b12e4d3bb8df994f042ff1216fb8de2b967aab9e (about one year ago).

#### The implementation of `avio_context_free`
```c++
void avio_context_free(AVIOContext **ps)
{
    av_freep(ps);
}
```

#### My patch;
I haven't grokked pointers yet, so I'd appreciate if someone could have a look at it.
Seems to be working for me, but I assume this could be leaking memory if I screwed it up.
```diff
diff --git a/server2.c b/server2.c
index 87343b5..c7a10ea 100644
--- a/server2.c
+++ b/server2.c
@@ -222,7 +222,8 @@ void write_segment(struct Client *c)
         avformat_close_input(&fmt_ctx);
         av_free(avio_ctx->buffer);
         avformat_free_context(fmt_ctx);
-        avio_context_free(&avio_ctx);
+        av_freep(&avio_ctx);
         buffer_drop_segment(c->buffer);
         client_set_state(c, WRITABLE);
     } else {
```

**Comment by phillmac** [comment]
Change the server definition to read         
`$(CC) -g -Wall $(LAV_CFLAGS) -pthread -o server segment.o buffer.o publisher.o server2.c $(LAV_LDFLAGS)`
LAV_LDFLAGS must go at the tail of the command for some reason

**Comment by Tilakv** [comment]
I still see the same error. /ffmpeg/libavutil/hwcontext_vdpau.c:431: undefined reference to `XOpenDisplay'
undefined reference to `XDisplayString'
undefined reference to `XDefaultScreen'

I am using the latest master and tried to compile with the ffmpeg git from version N-91447
I have the dependencies updated and the libraries.

**Comment by klaxa** [comment]
This seems rather unrelated to the project. Your error appears to indicate that you are missing some development-headers relating to Xorg (?). I'm not sure how I can help with that extensively. Have you tried following a compilation guide? ( https://trac.ffmpeg.org/wiki/CompilationGuide )

**Comment by Tilakv** [comment]
Yes, I have compiled it through the https://trac.ffmpeg.org/wiki/CompilationGuide. 
My idea was to stream the pipe of images to HTML5 client, and it worked with ffserver, which no longer exists. Does mkvserver write to webm file readable by HTML5 video Tag? I have used ffmpeg to stream as http:localhost:8090 but html5 cannot connect to the stream and the port seems to be closed. I suppose http streaming with current ffmpeg version is still experimental? I used the following commandline:

VP9_LIVE_PARAMS="-threads 1  -deadline realtime -lag-in-frames 0"
/home/user/bin/ffmpeg  -f rawvideo  -vcodec rawvideo -pix_fmt bgr24 -video_size 512x512 -probesize 32 -r 100 -i /home/user/raw_render/src/image_out -vcodec libvpx  -vf vflip -b:v 2000k   -g 1 ${VP9_LIVE_PARAMS} -listen 1 -f webm  http://10.0.0.10:8090

Thanks for reading !
